### PR TITLE
whipped autotools into shape, updated debian packaging

### PR DESCRIPTION
**Pull request by barak**

### CODE REVIEW

**Comment by barak** [comment]
(on the queue would be generating config.h: move existing config.h out of way, resolve related issues, get associated stuff out of Makefile.am, etc.  But as is should be good enough for all current modern systems, I think.)

**Comment by rbrito** [comment]
Hi, Barak.

First of all, thank you very much for this. I had neglected the generation of the autotools stuff, since my autotools-fu is next to zero, but reading your step-by-step comments made things easier to understand part of the modus operandi.

I have some specific comments about minor style things but your changes are _superb_. And, BTW, if you could help with the better factorization of what you mentioned regarding `config.h`, that would be amazing.

I'm merging your changes now.

Thanks so much.

**Comment by barak** [comment]
i think the current config.h should be renamed, and the renamed file #included instead.
Then #include "config.h" should be added, and config.h should be generated using the usual autotools mechanisms.
Then something can be done about the version number (ahem) and that would be about that.

BTW, should this be renamed, perhaps xpdf-poppler, so it can be uploaded into Debian without colliding with the current xpdf package?

**Comment by rbrito** [comment]
Right. I can, of course, rename the current config.h to something else and #include in. OTOH, I am not sure how to use autotools for generation of a "real" config.h. Can you handhold me here?

Regarding the renaming of the package to include it in Debian, I am all for it. Would you like to upload it or sponsor it (with co-maintenance)?

**Comment by barak** [comment]
Yes, happy to upload it to Debian.  Let me know when you think it's ready.
(Will rename config.h and tickle autotools to create one.)

**Comment by rbrito** [comment]
Hi, Barak.

Can you send me a pull request with the commits that you want me to merge? I am thinking of doing some final rounds before tagging the first alpha of xpdf-poppler and your changes will surely be in.

Thanks.

**Comment by barak** [comment]
all of 'em, assuming you want to do the rename?

**Comment by rbrito** [comment]
Just for the record, they were merged.

Just thinking of doing a rename of the source files inside a src directory, now that we are using a "heavier" infrastructure than a simple `Makefile` (like in the past).

Thanks.

**Pull request merged**
